logging:
  level: INFO
  loggers:
    org.uploader.dilitrust: DEBUG

template: Hello, %s!

defaultName: thierno

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8087
    #- type: https
    #  port: 8446
    #  keyStorePath: example.keystore
    #  keyStorePassword: example
    #this requires the alpn-boot library on the JVM's boot classpath
    #- type: h2
    #  port: 8445
    #  keyStorePath: example.keystore
    #  keyStorePassword: example
  adminConnectors:
    - type: http
      port: 8088
    #- type: https
    #  port: 8447
    #  keyStorePath: example.keystore
     # keyStorePassword: example
